###
GET http://localhost:3003/api/blogs

GET http://localhost:3003/api/blogs/info

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

    {
        "title": "The Power of Positive Thinking",
        "author": "Jane Doe",
        "url": "https://example.com/blog/power-positive-thinking"
    }

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

    {
        "title": "Mastering Time Management",
        "author": "Michael Johnson",
        "url": "https://example.com/blog/mastering-time-management",
        "likes": 33
    }

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

    {
        "title": "Introduction to Machine Learning",
        "author": "Emily Williams",
        "url": "https://example.com/blog/intro-to-machine-learning",
        "likes": 68
    }

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

    {
        "title": "Healthy Eating Habits for a Busy Lifestyle",
        "author": "Alex Carter",
        "url": "https://example.com/blog/healthy-eating-habits",
        "likes": 12
    }

###
DELETE http://localhost:3003/api/blogs/64e4a9ddbf110317702bcb81

###
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/64de05e3daad8af0623fca49
Content-Type: application/json
    
    {
        "author": "nobody",
       "likes": 9999
    }


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndlczIxIiwiaWQiOiI2NGRmMWEwOTY4MjZkYTI0ZDllMzFkNjMiLCJpYXQiOjE2OTI3MDIzNzl9.P_R8B_n5tuB5pxzg09SNEqY_NwzWawSEA5Rdq3h4X1I

    {
        "title": "Healthy Eating Habits for a Busy Lifestyle",
        "author": "Alex Carter",
        "url": "https://example.com/blog/healthy-eating-habits",
        "likes": 12
    }
